### ISSUE TITLE
Down link extra telemetry

### ISSUE THREAD

**Issue by jonathanmichel** [daveake/flextrak#1]
According to the [FlexTrak manual](https://github.com/daveake/HAB-Documentation/blob/main/FlexTrak%20Manual.pdf), there is a way to downlink extra telemetry through the flexavr. However, I'm not sure how it is supposed to be done. The [extra_telemetry()](https://github.com/daveake/flextrak/blob/7fc1bfde341e08b5b956efc22ed70fe180e78646/tracker.py#L4) function seems to be unused and I was not able to locate how it is handled in the [flexavr](https://github.com/daveake/flexavr) code. 

In the manual, it is indacated that "Changing fieldlist is an advanced subject that will be covered in a separate document". Any additionnal information on that ? 

Thanks !

**Comment by daveake** [comment]
The required changes to support custom fields have been made and will be
released later this week, together with an updated manual.

**Comment by jonathanmichel** [comment]
Great, thank you for your fast reponse !

**Comment by jonathanmichel** [comment]
Btw I tried to reprogram the flexavr in order to add features. I was able to build and send the compiled `.hex.ino` through serial. However, I now have an issue with the serial communication. If I check serial reception with picocom, it seems to have an encodage (?) issue with the line. Any idea ? I took the last version of the code on the [flexavr](https://github.com/daveake/flexavr) GitHub. 

[](url)
![format](https://user-images.githubusercontent.com/24658882/114559720-50be9380-9c6c-11eb-9062-5baa40b1809f.png)

**Comment by daveake** [comment]
Odd.  I'll send you the latest tomorrow then you'll have the custom fields.

**Comment by jonathanmichel** [comment]
Thanks ! I will continue to try to fix my issue. I have custom needs (in addition to custom fields) that could require a firmware update in the future. Keep you posted if I found anything.


De : David Akerman
Envoyé le :mardi, 13 avril 2021 15:54
À : daveake/flextrak
Cc : Jonathan Michel; Author
Objet :Re: [daveake/flextrak] Down link extra telemetry (#1)

Odd. I'll send you the latest tomorrow then you'll have the custom fields.

**Comment by daveake** [comment]
In that case build from source in Arduino, then copy the resulting hex file
to the Pi and organ the board from there.  If you need custom firmware
you'll need to do this sooner or later.

**Comment by jonathanmichel** [comment]
Yep I did, the compilation and programmation work correctly. Just the serial line that is strange. It seems to be a baudrate issue, I’m sometimes able to decode received char and sometimes not. 

De : David Akerman
Envoyé le :mardi, 13 avril 2021 16:28
À : daveake/flextrak
Cc : Jonathan Michel; Author
Objet :Re: [daveake/flextrak] Down link extra telemetry (#1)

In that case build from source in Arduino, then copy the resulting hex file
to the Pi and organ the board from there. If you need custom firmware
you'll need to do this sooner or later.

**Comment by daveake** [comment]
I don't get why it would work sometimes and not others.

The firmware sets 38400 baud and you have the same in that terminal
program, so that should be that.  I common mistake (in my experience ...)
is to forget to set the processor speed in Arduino IDE, so then you get a
base rate that is half what you wanted (because Arduino defaults to 16MHz
for the 328p and it's actually 8MHz).  But this would not be an
intermittent issue.

**Comment by daveake** [comment]
Oh, and make sure that the Python program isn't running when you return the
device or when you run a terminal program, so you don't get multiple
programs accessing the serial port at once.

**Comment by jonathanmichel** [comment]
Good call concerning the processor speed. In fact, I'm using VSCode to verify, send and program the AVR and I found that it uses the default configuration for the 328p (16MHz). Before noticing, I was indeed able to figure out that 19200 works for the serial line:

_Custom firmware printing the AVR version each second_

![19200o](https://user-images.githubusercontent.com/24658882/114573743-ee1fc480-9c78-11eb-903b-10021ea4d439.png)

But sometimes it doesn't. This intermittent behaviour is quite strange:
![19200n](https://user-images.githubusercontent.com/24658882/114573733-ebbd6a80-9c78-11eb-99ec-a3c408356266.png)

I'll check in VSCode how to change the processor speed and try to understand why my issue is not constant.

Thank you for your help!

**Comment by daveake** [comment]
It's just rebooting rather than running?

**Comment by jonathanmichel** [comment]
The avr board? It reboots after reprogramming so it should be ok. Not sure what you mean.

In any case, I made a custom card in the Arduino board.txt file copied from the Nano one but with a CPU frequency @8Mhz. Now it works, no more intermittent issues. It is strange, I never changed the serial speed in the avr code so even with the CPU freq issue it should be constantly working at 19200… Anyway I'll see in the future.

Keep me posted concerning the custom fields, thanks!

**Comment by daveake** [comment]
It looked like there were several this in the comms window.

Of that you need a custom file.  I build on a PC, withing the Arduino IDE,
with the board type set to Arduino Mini Pro and the CPU to 328p / 3V3 /
8MHz.

Dave

**Comment by 001Mario** [comment]
Surprisingly, I came across the same issue today - also wanting to add extra telemetry for a custom downlink message. What a coincidence that someone asked this just yesterday! :)

I tried to implement this using the callback `set_sentence_callback` from the `Tracker`-class, e.g.
```python
# tracker.py
def extra_telemetry:
    return "my,extra,telemetry"

# ... some more code here ...

mytracker.set_sentence_callback(extra_telemetry)
```` 
but then I realized that the `SentenceCallback`-function is actually never called (or have I overlook something?)
Anyway, thanks a lot & I'm looking forward to the update!

**Comment by daveake** [comment]
Yes, it's not called, it was never implemented that way.  New version will
be out on Friday.

**Comment by 001Mario** [comment]
Great, thank you very much indeed!

**Comment by jonathanmichel** [comment]
Thank you for the V1.20 update ! 

I saw that you also uncommented part of the code concerning uplink. Any news on that side ?

I currently have the [LoRaGo OTG](https://store.uputronics.com/index.php?route=product/product&product_id=111) module as a receiver. According to the [Lora Serial Protocol](https://github.com/daveake/HAB-Documentation/blob/main/LoRa%20Serial%20Protocol.pdf) I should be able to transmit text by sending `~T<text>` over the serial line. I made a few tests but received `?` as a response. (Same when I send `D` and `V` btw, which is strange, other commands work correctly). I trie to reprogram the LoRaGo module with the [LoRaArduinoSerial](https://github.com/daveake/LoRaArduinoSerial) code, but was unable to do it, probably due to programming restriction. I could be interrested in using it for uplink too!

**Comment by daveake** [comment]
You'll need to update the OTG firmware for uplink support.  If you're
unable to do it you can send it to me and I'll reprogram it.

Dave

**Comment by jonathanmichel** [comment]
Any chance I could do it on my side ?
I opened it and identified the ATmega32U4 with a 6-pins connector, I suppose I can't reprogram it over USB and should use this one. Is that right ? But I would need additional information for the Arduino IDE configuration. Thanks !

**Comment by daveake** [comment]
Yes in the IDE you select a 32U4 CPU e.g. the Adafruit feather.  I always
program via the connector as I had trouble programming it through USB.  The
connector is for a special plug/cable which if I remember is around £20,
however if you don't mind soldering you could make up an adapter to fit an
AVR ISP.

I'm happy to program it for you FOC.

Dave

**Comment by daveake** [comment]
Can you  take this to email please ***@***.*** - it's not a Flextrak
issue :)

Dave

**Comment by jonathanmichel** [comment]
Ok noted, i keep you posted. And I close the issue sorry !
