### ISSUE TITLE
Update to sondehub

### ISSUE THREAD

**Issue by ator1811** [daveake/flextrak#3]
Do you have plans to add the  SendFieldList option to this flextrak (we have the old version of RPi/avr flextrak) to be able to send to Sondehub (including flexavr)?

**Comment by daveake** [comment]
You can still use Sondehub but it won't show temperature etc., just the
basic GPS telemetry.

But in answer to your question, yes, probably later this week.

Dave

**Comment by ator1811** [comment]
Ok, thx

**Comment by daveake** [comment]
Added in V1.22, released today.  Python side to be released shortly.
